#RabbitMQ
# A porta 15672 é a porta da interface grafica
# A porta onde do Rabbitmq esta rodando é a 5672
server:
  port: 8081
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchenge:
        producer: ex.producer.aula-spring
      routing-key:
        producer: rk.producer.aula-spring
      dead-letter:
        producer: dl.producer.aula-spring
      parking-lot:
        producer: pl.producer.aula-spring.producer.aula-spring